# Generated by Django 5.1.1 on 2024-09-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0016_remove_accountmodel_django_ledg_coa_mod_e19964_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtransactionmodel',
            name='unit_cost_currency',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Currency'),
        ),
    ]
